import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const lora = localFont({
  src: [
    { path: "./fonts/lora/Lora-Regular.ttf", weight: "400", style: "normal" },
    // add more weights/styles as needed:
    // { path: "./fonts/Lora-Bold.woff2", weight: "700", style: "normal" },
    // { path: "./fonts/Lora-Italic.woff2", weight: "400", style: "italic" },
  ],
  variable: "--font-lora", // 👈 CSS var to expose the font
  display: "swap",
});

const montserrat = localFont({
  src: [
    {
      path: "./fonts/montserrat/Montserrat-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-montserrat", // 👈 CSS var to expose the font
  display: "swap",
});

const montserratBold = localFont({
  src: [
    {
      path: "./fonts/montserrat/Montserrat-Bold.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-montserrat-bold", // 👈 CSS var to expose the font
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lora.variable} ${montserrat.variable}  ${montserratBold.variable}  font-montserrat  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
